-- Seed Categories
INSERT INTO categories (id, name, slug, description) VALUES
(1, 'Politik', 'politik', 'Berita politik nasional, hukum, kebijakan pemerintah, dan hubungan internasional.'),
(2, 'Bisnis', 'bisnis', 'Informasi pasar keuangan, investasi, ekonomi makro, dan perkembangan bisnis tanah air.'),
(3, 'Teknologi', 'teknologi', 'Perkembangan gadget terbaru, startup, kecerdasan buatan, sains, dan inovasi digital.'),
(4, 'Hiburan', 'hiburan', 'Berita musik, film, gaya hidup, festival seni, dan kehidupan selebritas.'),
(5, 'Olahraga', 'olahraga', 'Liputan kompetisi sepak bola, bulu tangkis, balapan, olahraga ekstrem, dan gaya hidup sehat.')
ON CONFLICT (id) DO NOTHING;

-- Reset SERIAL sequence for categories
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));

-- Seed Articles
INSERT INTO articles (id, title, slug, excerpt, content, image_url, category_id, author, published_at, view_count, is_featured, is_breaking, reading_time_minutes) VALUES
(1, 'Pembangunan IKN Nusantara Tahap 2 Resmi Dimulai, Fokus Pusat Olahraga dan Hunian', 'pembangunan-ikn-nusantara-tahap-2-resmi-dimulai-fokus-pusat-olahraga-dan-hunian', 'Pemerintah resmi memulai proyek pembangunan Ibu Kota Nusantara (IKN) tahap kedua dengan alokasi anggaran Rp25 Triliun yang berfokus pada infrastruktur publik dan hunian ASN.', '<p><strong>Nusantara, NGN Portal</strong> — Kementerian Pekerjaan Umum dan Perumahan Rakyat (PUPR) secara resmi mengumumkan dimulainya pembangunan Ibu Kota Nusantara (IKN) Tahap 2.</p><p>Fase kedua ini akan sangat berfokus pada pembangunan kompleks olahraga terpadu (sports center), gedung-gedung perkantoran baru, serta hunian berkelanjutan untuk para Aparatur Sipil Negara (ASN) yang akan mulai dipindahkan secara masif akhir tahun ini.</p><p>Menteri PUPR menjelaskan bahwa pembangunan ini ditargetkan rampung pada awal tahun 2027 dengan melibatkan lebih dari 50 kontraktor lokal dan internasional yang berkomitmen menjaga lingkungan hidup sekitar IKN.</p><p>Pusat olahraga yang akan dibangun memiliki fasilitas berstandar Olimpiade, mencakup stadion utama berkapasitas 50.000 penonton, arena akuatik, hingga jalur khusus atletik dan bersepeda.</p><p>Langkah ini diharapkan tidak hanya menjadikan IKN sebagai pusat pemerintahan saja, melainkan juga pusat peradaban baru Indonesia yang aktif, sehat, dan ramah lingkungan.</p>', 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=1200', 1, 'Andi Wijaya', NOW(), 1250, TRUE, FALSE, 3),

(2, 'Rupiah Menguat Tajam ke Rp15.200 per Dolar AS Pasca Penurunan Suku Bunga Fed', 'rupiah-menguat-tajam-ke-rp15200-per-dolar-as-pasca-penurunan-suku-bunga-fed', 'Mata uang Rupiah mencatat penguatan signifikan terhadap dolar AS menyusul keputusan The Fed menurunkan suku bunga sebesar 50 basis poin.', '<p><strong>Jakarta, NGN Portal</strong> — Nilai tukar rupiah terhadap dolar AS ditutup menguat tajam pada perdagangan sore ini di level Rp15.200 per dolar AS. Penguatan ini dipicu oleh sentimen positif pasar global setelah bank sentral Amerika Serikat, Federal Reserve (The Fed), menurunkan suku bunga acuan sebesar 50 basis poin.</p><p>Gubernur Bank Indonesia (BI) menyatakan bahwa penguatan rupiah ini juga didukung oleh kondisi fundamental ekonomi domestik yang sangat solid, tingkat inflasi yang terjaga, serta cadangan devisa yang melimpah.</p><p>Para analis memproyeksikan rupiah masih berpotensi menguat hingga di bawah level Rp15.000 per dolar AS dalam beberapa minggu ke depan jika aliran modal asing terus masuk ke pasar surat utang negara dan pasar saham dalam negeri secara konsisten.</p>', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=800', 2, 'Rina Susanti', NOW() - INTERVAL '2 hours', 840, FALSE, FALSE, 2),

(3, 'Meluncur di Indonesia, Ponsel Lipat NGN Pro Hadirkan Teknologi Layar Gulung Pertama', 'meluncur-di-indonesia-ponsel-lipat-ngn-pro-hadirkan-teknologi-layar-gulung-pertama', 'NGN meluncurkan smartphone flagship NGN Pro dengan inovasi layar gulung (rollable display) tercanggih di kelasnya.', '<p><strong>Jakarta, NGN Portal</strong> — Industri teknologi tanah air kembali bergairah dengan peluncuran resmi ponsel flagship terbaru NGN Pro. Perangkat ini menjadi pelopor di Indonesia dengan mengintegrasikan teknologi layar gulung (rollable) dan lipat secara bersamaan.</p><p>Menggunakan panel OLED fleksibel generasi terbaru, NGN Pro mampu meregangkan layarnya dari ukuran 6,7 inci menjadi tablet ringkas berukuran 8,2 inci hanya dengan menekan satu tombol navigasi di bagian samping perangkat.</p><p>Didukung oleh chipset kelas atas Snapdragon 8 Gen 5 dan baterai 5.500 mAh dengan pengisian daya super cepat 120W, NGN Pro menyasar segmen premium dengan harga mulai dari Rp24.999.000.</p><p>Inovasi ini dinilai mengubah cara konsumen menikmati konten multimedia dan bekerja secara mobile.</p>', 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800', 3, 'Budi Pratama', NOW() - INTERVAL '4 hours', 2100, FALSE, TRUE, 3),

(4, 'Konser Akbar Band Indonesia di Gelora Bung Karno Sedot 80 Ribu Penonton', 'konser-akbar-band-indonesia-di-gelora-bung-karno-sedot-80-ribu-penonton', 'Konser reuni spektakuler salah satu band legendaris Indonesia berhasil memukau puluhan ribu penggemar di Stadion GBK.', '<p><strong>Jakarta, NGN Portal</strong> — Stadion Utama Gelora Bung Karno (GBK) bergemuruh hebat pada Sabtu malam lalu. Konser reuni band legendaris tanah air berhasil menarik perhatian lebih dari 80.000 penonton dari seluruh penjuru Indonesia.</p><p>Dengan tata panggung megah berukuran raksasa dan permainan visual lampu laser yang dramatis, band ini membawakan total 25 lagu hits terbaik mereka selama hampir 3 jam tanpa henti.</p><p>Penonton terlihat larut dalam nostalgia dan menyanyi bersama sepanjang jalannya konser yang berlangsung dengan tertib, aman, dan sangat berkesan.</p>', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=800', 4, 'Siti Aminah', NOW() - INTERVAL '12 hours', 980, FALSE, FALSE, 2),

(5, 'Timnas Sepak Bola Indonesia Lolos ke Semifinal Piala Asia 2026, Sejarah Baru!', 'timnas-sepak-bola-indonesia-lolos-ke-semifinal-piala-asia-2026-sejarah-baru', 'Perjuangan luar biasa skuad Garuda membuahkan hasil dengan lolos pertama kalinya ke semifinal Piala Asia setelah mengalahkan lawan kuat.', '<p><strong>Doha, NGN Portal</strong> — Skuad Garuda sukses mengukir tinta emas dalam sejarah sepak bola tanah air. Tim Nasional Indonesia berhasil lolos ke babak semifinal Piala Asia 2026 setelah menaklukkan salah satu raksasa sepak bola Asia melalui adu penalti yang dramatis.</p><p>Pelatih memuji disiplin tinggi dan semangat pantang menyerah yang ditunjukkan oleh anak asuhnya sepanjang 120 menit jalannya pertandingan yang berlangsung sangat sengit.</p><p>Jutaan masyarakat di Indonesia menggelar nonton bareng di berbagai kota besar untuk merayakan kemenangan bersejarah ini.</p>', 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800', 5, 'Feri Irawan', NOW() - INTERVAL '1 day', 3450, FALSE, FALSE, 2),

(6, 'Kementerian BUMN Resmikan Program Inkubator Startup Teknologi Hijau', 'kementerian-bumn-resmikan-program-inkubator-startup-teknologi-hijau', 'Program inkubator ini ditujukan untuk mendukung startup lokal yang berfokus pada solusi ramah lingkungan dan energi terbarukan.', '<p><strong>Jakarta, NGN Portal</strong> — Kementerian BUMN meresmikan program inkubator baru khusus untuk startup di bidang teknologi hijau (green tech). Program ini dirancang guna mendukung target Indonesia mencapai emisi nol bersih pada tahun 2060.</p><p>Sebanyak 20 startup terpilih akan menerima bimbingan intensif dari para ahli industri, akses ke jaringan BUMN, serta pendanaan tahap awal hingga Rp5 Miliar per perusahaan untuk mempercepat komersialisasi inovasi ramah lingkungan.</p>', 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=800', 2, 'Rina Susanti', NOW() - INTERVAL '1.5 days', 450, FALSE, FALSE, 2),

(7, 'Apple Vision Pro 2 Resmi Diumumkan dengan Sensor Baru, Lebih Ringan', 'apple-vision-pro-2-resmi-diumumkan-dengan-sensor-baru-lebih-ringan', 'Apple resmi meluncurkan headset spasial generasi kedua mereka dengan peningkatan kenyamanan dan harga yang lebih terjangkau.', '<p><strong>California, NGN Portal</strong> — Apple secara mengejutkan merilis lini produk terbaru mereka, Vision Pro 2. Mengatasi keluhan utama generasi pertama, headset ini 20% lebih ringan berkat material komposit terbaru.</p><p>Vision Pro 2 juga dilengkapi dengan sensor pelacak gerakan mata yang lebih presisi dan resolusi layar micro-OLED yang ditingkatkan demi menghadirkan pengalaman komputasi spasial yang jauh lebih mulus dan nyata.</p>', 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=800', 3, 'Budi Pratama', NOW() - INTERVAL '2 days', 1890, FALSE, FALSE, 2),

(8, 'Film Drama Keluarga Karya Sutradara Lokal Tembus Festival Film Cannes', 'film-drama-keluarga-karya-sutradara-lokal-tembus-festival-film-cannes', 'Prestasi membanggakan kembali diraih dunia perfilman Indonesia, satu film drama keluarga masuk kompetisi utama Cannes.', '<p><strong>Cannes, NGN Portal</strong> — Karya sinema anak bangsa kembali mendapat pengakuan internasional di panggung bergengsi Festival Film Cannes. Film drama keluarga yang mengangkat isu sosial di pedalaman Indonesia terpilih masuk dalam kategori utama.</p><p>Sutradara mengaku sangat bersyukur dan berharap pencapaian ini dapat membuka jalan bagi lebih banyak sineas tanah air untuk mendistribusikan karya orisinal mereka ke pasar dunia.</p>', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800', 4, 'Siti Aminah', NOW() - INTERVAL '3 days', 560, FALSE, FALSE, 2),

(9, 'Juara Dunia Bulu Tangkis Indonesia Pertahankan Gelar di All England 2026', 'juara-dunia-bulu-tangkis-indonesia-pertahankan-gelar-di-all-england-2026', 'Ganda putra andalan Indonesia kembali naik podium tertinggi setelah menaklukkan pasangan unggulan asal Tiongkok.', '<p><strong>Birmingham, NGN Portal</strong> — Tradisi emas bulu tangkis Indonesia di turnamen All England terus berlanjut. Ganda putra andalan Indonesia sukses mempertahankan gelar juara mereka setelah memenangkan laga final yang menegangkan.</p><p>Melalui perjuangan tiga gim yang melelahkan, pasangan Indonesia berhasil membuktikan ketahanan fisik dan mental juara mereka di hadapan publik Arena Birmingham yang gemuruh.</p>', 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800', 5, 'Feri Irawan', NOW() - INTERVAL '4 days', 1120, FALSE, FALSE, 2),

(10, 'Rapat Paripurna DPR RI Sahkan Undang-Undang Perlindungan Data Pribadi Baru', 'rapat-paripurna-dpr-ri-sahkan-undang-undang-perlindungan-data-pribadi-baru', 'DPR RI resmi mengetok palu pengesahan regulasi baru perlindungan data pribadi demi menekan angka kebocoran data di ruang digital.', '<p><strong>Jakarta, NGN Portal</strong> — Dewan Perwakilan Rakyat (DPR) RI secara resmi menyetujui pengesahan Undang-Undang Perlindungan Data Pribadi (UU PDP) yang baru. Regulasi ini memuat sanksi denda yang jauh lebih berat bagi korporasi yang terbukti lalai mengamankan data pengguna.</p><p>UU baru ini diharapkan dapat memperkuat ekosistem keamanan siber nasional dan melindungi jutaan pengguna internet di Indonesia dari ancaman kebocoran data.</p>', 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=800', 1, 'Andi Wijaya', NOW() - INTERVAL '5 days', 1050, FALSE, FALSE, 2)
ON CONFLICT (id) DO NOTHING;

-- Reset SERIAL sequence for articles
SELECT setval('articles_id_seq', (SELECT MAX(id) FROM articles));

-- Seed Breaking News Ticker Items
INSERT INTO breaking_news (id, text, is_active, article_id) VALUES
(1, 'BREAKING: Skuad Garuda cetak sejarah lolos ke semifinal Piala Asia 2026 setelah drama adu penalti!', TRUE, 5),
(2, 'INFO: Nilai tukar rupiah melesat tajam hari ini, sentuh Rp15.200 per dolar AS.', TRUE, 2),
(3, 'NEW: Smartphone layar gulung premium NGN Pro resmi dirilis di Indonesia!', TRUE, 3)
ON CONFLICT (id) DO NOTHING;

-- Reset SERIAL sequence for breaking_news
SELECT setval('breaking_news_id_seq', (SELECT MAX(id) FROM breaking_news));
