import { Article, Category, BreakingNews } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Politik',
    slug: 'politik',
    description: 'Berita politik nasional, hukum, kebijakan pemerintah, dan hubungan internasional.',
    created_at: new Date().toISOString(),
    articleCount: 2,
  },
  {
    id: 2,
    name: 'Bisnis',
    slug: 'bisnis',
    description: 'Informasi pasar keuangan, investasi, ekonomi makro, dan perkembangan bisnis tanah air.',
    created_at: new Date().toISOString(),
    articleCount: 2,
  },
  {
    id: 3,
    name: 'Teknologi',
    slug: 'teknologi',
    description: 'Perkembangan gadget terbaru, startup, kecerdasan buatan, sains, dan inovasi digital.',
    created_at: new Date().toISOString(),
    articleCount: 2,
  },
  {
    id: 4,
    name: 'Hiburan',
    slug: 'hiburan',
    description: 'Berita musik, film, gaya hidup, festival seni, dan kehidupan selebritas.',
    created_at: new Date().toISOString(),
    articleCount: 2,
  },
  {
    id: 5,
    name: 'Olahraga',
    slug: 'olahraga',
    description: 'Liputan kompetisi sepak bola, bulu tangkis, balapan, olahraga ekstrem, dan gaya hidup sehat.',
    created_at: new Date().toISOString(),
    articleCount: 2,
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 1,
    title: 'Pemerintah Resmikan Ibu Kota Nusantara Tahap Kedua, 20 Ribu ASN Siap Pindah',
    slug: 'pemerintah-resmikan-ibu-kota-nusantara-tahap-kedua-20-ribu-asn-siap-pindah',
    excerpt: 'Presiden meresmikan fase kedua pembangunan IKN yang mencakup pusat pemerintahan, sementara puluhan ribu aparatur sipil negara bersiap melakukan relokasi.',
    content: '<p><strong>Jakarta, NGN Portal</strong> — Pemerintah hari ini resmi memulai tahap kedua pembangunan Ibu Kota Nusantara (IKN) di Kalimantan Timur. Fase ini mencakup pembangunan pusat pemerintahan, perumahan menteri, dan berbagai fasilitas publik pendukung.</p><p>Sebanyak 20.000 Aparatur Sipil Negara (ASN) telah menyatakan kesiapannya untuk pindah ke IKN pada gelombang pertama relokasi. Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi menegaskan bahwa seluruh fasilitas penunjang, termasuk perumahan dan sekolah, telah siap digunakan.</p><p>Pembangunan tahap kedua ini menandai babak baru dalam sejarah perpindahan ibu kota negara Indonesia.</p>',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800',
    category_id: 1,
    author: 'Ahmad Faizal',
    published_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    view_count: 1500,
    is_featured: true,
    is_breaking: false,
    reading_time_minutes: 3,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Politik',
  },
  {
    id: 2,
    title: 'Rupiah Menguat Tajam ke Rp15.200 per Dolar AS Pasca Penurunan Suku Bunga Fed',
    slug: 'rupiah-menguat-tajam-ke-rp15200-per-dolar-as-pasca-penurunan-suku-bunga-fed',
    excerpt: 'Mata uang Rupiah mencatat penguatan signifikan terhadap dolar AS menyusul keputusan The Fed menurunkan suku bunga sebesar 50 basis poin.',
    content: '<p><strong>Jakarta, NGN Portal</strong> — Nilai tukar rupiah terhadap dolar AS ditutup menguat tajam pada perdagangan sore ini di level Rp15.200 per dolar AS. Penguatan ini dipicu oleh sentimen positif pasar global setelah bank sentral Amerika Serikat, Federal Reserve (The Fed), menurunkan suku bunga acuan sebesar 50 basis poin.</p><p>Gubernur Bank Indonesia (BI) menyatakan bahwa penguatan rupiah ini juga didukung oleh kondisi fundamental ekonomi domestik yang sangat solid, tingkat inflasi yang terjaga, serta cadangan devisa yang melimpah.</p><p>Para analis memproyeksikan rupiah masih berpotensi menguat hingga di bawah level Rp15.000 per dolar AS dalam beberapa minggu ke depan jika aliran modal asing terus masuk ke pasar surat utang negara dan pasar saham dalam negeri secara konsisten.</p>',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=800',
    category_id: 2,
    author: 'Rina Susanti',
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    view_count: 840,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Bisnis',
  },
  {
    id: 3,
    title: 'Meluncur di Indonesia, Ponsel Lipat NGN Pro Hadirkan Teknologi Layar Gulung Pertama',
    slug: 'meluncur-di-indonesia-ponsel-lipat-ngn-pro-hadirkan-teknologi-layar-gulung-pertama',
    excerpt: 'NGN meluncurkan smartphone flagship NGN Pro dengan inovasi layar gulung (rollable display) tercanggih di kelasnya.',
    content: '<p><strong>Jakarta, NGN Portal</strong> — Industri teknologi tanah air kembali bergairah dengan peluncuran resmi ponsel flagship terbaru NGN Pro. Perangkat ini menjadi pelopor di Indonesia dengan mengintegrasikan teknologi layar gulung (rollable) dan lipat secara bersamaan.</p><p>Menggunakan panel OLED fleksibel generasi terbaru, NGN Pro mampu meregangkan layarnya dari ukuran 6,7 inci menjadi tablet ringkas berukuran 8,2 inci hanya dengan menekan satu tombol navigasi di bagian samping perangkat.</p><p>Didukung oleh chipset kelas atas Snapdragon 8 Gen 5 dan baterai 5.500 mAh dengan pengisian daya super cepat 120W, NGN Pro menyasar segmen premium dengan harga mulai dari Rp24.999.000.</p><p>Inovasi ini dinilai mengubah cara konsumen menikmati konten multimedia dan bekerja secara mobile.</p>',
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800',
    category_id: 3,
    author: 'Budi Pratama',
    published_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    view_count: 2100,
    is_featured: false,
    is_breaking: true,
    reading_time_minutes: 3,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Teknologi',
  },
  {
    id: 4,
    title: 'Konser Akbar Band Indonesia di Gelora Bung Karno Sedot 80 Ribu Penonton',
    slug: 'konser-akbar-band-indonesia-di-gelora-bung-karno-sedot-80-ribu-penonton',
    excerpt: 'Konser reuni spektakuler salah satu band legendaris Indonesia berhasil memukau puluhan ribu penggemar di Stadion GBK.',
    content: '<p><strong>Jakarta, NGN Portal</strong> — Stadion Utama Gelora Bung Karno (GBK) bergemuruh hebat pada Sabtu malam lalu. Konser reuni band legendaris tanah air berhasil menarik perhatian lebih dari 80.000 penonton dari seluruh penjuru Indonesia.</p><p>Dengan tata panggung megah berukuran raksasa dan permainan visual lampu laser yang dramatis, band ini membawakan total 25 lagu hits terbaik mereka selama hampir 3 jam tanpa henti.</p><p>Penonton terlihat larut dalam nostalgia dan menyanyi bersama sepanjang jalannya konser yang berlangsung dengan tertib, aman, dan sangat berkesan.</p>',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=800',
    category_id: 4,
    author: 'Siti Aminah',
    published_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    view_count: 980,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Hiburan',
  },
  {
    id: 5,
    title: 'Timnas Sepak Bola Indonesia Lolos ke Semifinal Piala Asia 2026, Sejarah Baru!',
    slug: 'timnas-sepak-bola-indonesia-lolos-ke-semifinal-piala-asia-2026-sejarah-baru',
    excerpt: 'Perjuangan luar biasa skuad Garuda membuahkan hasil dengan lolos pertama kalinya ke semifinal Piala Asia setelah mengalahkan lawan kuat.',
    content: '<p><strong>Doha, NGN Portal</strong> — Skuad Garuda sukses mengukir tinta emas dalam sejarah sepak bola tanah air. Tim Nasional Indonesia berhasil lolos ke babak semifinal Piala Asia 2026 setelah menaklukkan salah satu raksasa sepak bola Asia melalui adu penalti yang dramatis.</p><p>Pelatih memuji disiplin tinggi dan semangat pantang menyerah yang ditunjukkan oleh anak asuhnya sepanjang 120 menit jalannya pertandingan yang berlangsung sangat sengit.</p><p>Jutaan masyarakat di Indonesia menggelar nonton bareng di berbagai kota besar untuk merayakan kemenangan bersejarah ini.</p>',
    image_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800',
    category_id: 5,
    author: 'Feri Irawan',
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    view_count: 3450,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Olahraga',
  },
  {
    id: 6,
    title: 'Kementerian BUMN Resmikan Program Inkubator Startup Teknologi Hijau',
    slug: 'kementerian-bumn-resmikan-program-inkubator-startup-teknologi-hijau',
    excerpt: 'Program inkubator ini ditujukan untuk mendukung startup lokal yang berfokus pada solusi ramah lingkungan dan energi terbarukan.',
    content: '<p><strong>Jakarta, NGN Portal</strong> — Kementerian BUMN meresmikan program inkubator baru khusus untuk startup di bidang teknologi hijau (green tech). Program ini dirancang guna mendukung target Indonesia mencapai emisi nol bersih pada tahun 2060.</p><p>Sebanyak 20 startup terpilih akan menerima bimbingan intensif dari para ahli industri, akses ke jaringan BUMN, serta pendanaan tahap awal hingga Rp5 Miliar per perusahaan untuk mempercepat komersialisasi inovasi ramah lingkungan.</p>',
    image_url: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=800',
    category_id: 2,
    author: 'Rina Susanti',
    published_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    view_count: 450,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Bisnis',
  },
  {
    id: 7,
    title: 'Apple Vision Pro 2 Resmi Diumumkan dengan Sensor Baru, Lebih Ringan',
    slug: 'apple-vision-pro-2-resmi-diumumkan-dengan-sensor-baru-lebih-ringan',
    excerpt: 'Apple resmi meluncurkan headset spasial generasi kedua mereka dengan peningkatan kenyamanan dan harga yang lebih terjangkau.',
    content: '<p><strong>California, NGN Portal</strong> — Apple secara mengejutkan merilis lini produk terbaru mereka, Vision Pro 2. Mengatasi keluhan utama generasi pertama, headset ini 20% lebih ringan berkat material komposit terbaru.</p><p>Vision Pro 2 juga dilengkapi dengan sensor pelacak gerakan mata yang lebih presisi dan resolusi layar micro-OLED yang ditingkatkan demi menghadirkan pengalaman komputasi spasial yang jauh lebih mulus dan nyata.</p>',
    image_url: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=800',
    category_id: 3,
    author: 'Budi Pratama',
    published_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    view_count: 1890,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Teknologi',
  },
  {
    id: 8,
    title: 'Film Drama Keluarga Karya Sutradara Lokal Tembus Festival Film Cannes',
    slug: 'film-drama-keluarga-karya-sutradara-lokal-tembus-festival-film-cannes',
    excerpt: 'Prestasi membanggakan kembali diraih dunia perfilman Indonesia, satu film drama keluarga masuk kompetisi utama Cannes.',
    content: '<p><strong>Cannes, NGN Portal</strong> — Karya sinema anak bangsa kembali mendapat pengakuan internasional di panggung bergengsi Festival Film Cannes. Film drama keluarga yang mengangkat isu sosial di pedalaman Indonesia terpilih masuk dalam kategori utama.</p><p>Sutradara mengaku sangat bersyukur dan berharap pencapaian ini dapat membuka jalan bagi lebih banyak sineas tanah air untuk mendistribusikan karya orisinal mereka ke pasar dunia.</p>',
    image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800',
    category_id: 4,
    author: 'Siti Aminah',
    published_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    view_count: 560,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Hiburan',
  },
  {
    id: 9,
    title: 'Juara Dunia Bulu Tangkis Indonesia Pertahankan Gelar di All England 2026',
    slug: 'juara-dunia-bulu-tangkis-indonesia-pertahankan-gelar-di-all-england-2026',
    excerpt: 'Ganda putra andalan Indonesia kembali naik podium tertinggi setelah menaklukkan pasangan unggulan asal Tiongkok.',
    content: '<p><strong>Birmingham, NGN Portal</strong> — Tradisi emas bulu tangkis Indonesia di turnamen All England terus berlanjut. Ganda putra andalan Indonesia sukses mempertahankan gelar juara mereka setelah memenangkan laga final yang menegangkan.</p><p>Melalui perjuangan tiga gim yang melelahkan, pasangan Indonesia berhasil membuktikan ketahanan fisik dan mental juara mereka di hadapan publik Arena Birmingham yang gemuruh.</p>',
    image_url: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800',
    category_id: 5,
    author: 'Feri Irawan',
    published_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    view_count: 1120,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Olahraga',
  },
  {
    id: 10,
    title: 'Rapat Paripurna DPR RI Sahkan Undang-Undang Perlindungan Data Pribadi Baru',
    slug: 'rapat-paripurna-dpr-ri-sahkan-undang-undang-perlindungan-data-pribadi-baru',
    excerpt: 'DPR RI resmi mengetok palu pengesahan regulasi baru perlindungan data pribadi demi menekan angka kebocoran data di ruang digital.',
    content: '<p><strong>Jakarta, NGN Portal</strong> — Dewan Perwakilan Rakyat (DPR) RI secara resmi menyetujui pengesahan Undang-Undang Perlindungan Data Pribadi (UU PDP) yang baru. Regulasi ini memuat sanksi denda yang jauh lebih berat bagi korporasi yang terbukti lalai mengamankan data pengguna.</p><p>UU baru ini diharapkan dapat memperkuat ekosistem keamanan siber nasional dan melindungi jutaan pengguna internet di Indonesia dari ancaman kebocoran data.</p>',
    image_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=800',
    category_id: 1,
    author: 'Andi Wijaya',
    published_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    view_count: 1050,
    is_featured: false,
    is_breaking: false,
    reading_time_minutes: 2,
    created_at: new Date().toISOString(),
    status: 'published',
    category_name: 'Politik',
  },
];

export const MOCK_BREAKING_NEWS: BreakingNews[] = [
  {
    id: 1,
    text: 'BREAKING: Skuad Garuda cetak sejarah lolos ke semifinal Piala Asia 2026 setelah drama adu penalti!',
    is_active: true,
    article_id: 5,
    created_at: new Date().toISOString(),
    article_title: 'Timnas Sepak Bola Indonesia Lolos ke Semifinal Piala Asia 2026, Sejarah Baru!',
    article_slug: 'timnas-sepak-bola-indonesia-lolos-ke-semifinal-piala-asia-2026-sejarah-baru',
  },
  {
    id: 2,
    text: 'INFO: Nilai tukar rupiah melesat tajam hari ini, sentuh Rp15.200 per dolar AS.',
    is_active: true,
    article_id: 2,
    created_at: new Date().toISOString(),
    article_title: 'Rupiah Menguat Tajam ke Rp15.200 per Dolar AS Pasca Penurunan Suku Bunga Fed',
    article_slug: 'rupiah-menguat-tajam-ke-rp15200-per-dolar-as-pasca-penurunan-suku-bunga-fed',
  },
  {
    id: 3,
    text: 'NEW: Smartphone layar gulung premium NGN Pro resmi dirilis di Indonesia!',
    is_active: true,
    article_id: 3,
    created_at: new Date().toISOString(),
    article_title: 'Meluncur di Indonesia, Ponsel Lipat NGN Pro Hadirkan Teknologi Layar Gulung Pertama',
    article_slug: 'meluncur-di-indonesia-ponsel-lipat-ngn-pro-hadirkan-teknologi-layar-gulung-pertama',
  },
];

export function isSupabaseConfigured() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return !!(url && !url.includes('your-supabase-project') && !url.includes('example.com'));
}
